name: Update README on Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Docker Hub README
        run: |
          curl -X PATCH https://hub.docker.com/v2/repositories/jmeiracorbal/pdpe/ \
            -H "Content-Type: application/json" \
            -u "${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }}" \
            -d "{\"full_description\": \"$(jq -Rs . < README.md)\"}"
          